### PR TITLE
Catgen and varobs icons, desktop files and metadata files

### PR DESCRIPTION
**Pull request by mattiaverga**
Note that:
- I did not register a mimetype against catgen `.prj` files because that extension is too generic in my opinion. If you want to do that, we just need to add a recognizable header to the project files (for example, the first line of the file can be `<---Catgen project file--->`), so that we can specify the file extension + "the file starts with" when registering the mimetype.
- I couldn't find a varobs screenshot on the website, so the metadata file is not complete. It lacks a URL to a sample image.

### CODE REVIEW

**Comment by pchev** [comment]
Mattia,

Maybe the registration of .prj is not necessary. The advantage of using the command line is it allow to specify both the .prj file and the data file to process. 

Right, I never updated the Varobs information in the CdC web pages.
The only very old description (with Win95 screenshot!) is here:
http://www.astrosurf.com/astropc/oldversion/varobs/features.html

I refresh this page with new screenshot on the new site and I send you the URL. 
Maybe it is more easy if I wait for that before to merge, so the metadata can be completed.

**Comment by pchev** [comment]
Here the new page with screenshot you can link:
https://www.ap-i.net/skychart/en/documentation/varobs

**Comment by mattiaverga** [comment]
Done

**Comment by pchev** [comment]
Thank you very much!

**Pull request merged**
